# Generated by Django 5.2.7 on 2025-11-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_creator_calendar_event_id_todo_last_sync_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='creator_reminders',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='reminders',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
