# Generated by Django 5.2.7 on 2025-11-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todo_creator_reminders_todo_reminders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='creator_calendar_event_id',
            new_name='assignee_calendar_event_id',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='creator_reminders',
            new_name='assignee_reminders',
        ),
    ]
