# Generated by Django 5.2.7 on 2025-11-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_rename_creator_calendar_event_id_todo_assignee_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='assignee_calendar_event_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='calendar_event_active',
            field=models.BooleanField(default=True),
        ),
    ]
