# Generated by Django 5.2.7 on 2025-11-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_todo_assignee_calendar_event_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assignee_calendar_event_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='calendar_event_active',
            field=models.BooleanField(default=False),
        ),
    ]
