# Generated by Django 5.2.7 on 2025-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_alter_todo_assignee_calendar_event_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
