# Generated by Django 5.2.7 on 2025-12-04 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_todo_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'To Do', 'verbose_name_plural': 'To Dos'},
        ),
    ]
