# Generated by Django 5.2.7 on 2025-12-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_todo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('done', 'Done')], default='in progress', max_length=20),
        ),
    ]
