# Generated by Django 5.2.7 on 2025-10-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0003_consultationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={},
        ),
    ]
