# Generated by Django 5.2.7 on 2025-10-11 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0004_alter_consultationrequest_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequestSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='consultation_app.consultationrequest')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='request_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('request', 'student')},
            },
        ),
    ]
