# Generated by Django 5.2.7 on 2025-10-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0005_consultationrequestsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='closed_by_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
