# Generated by Django 5.2.7 on 2025-11-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0002_notification_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
