# Generated by Django 5.2.7 on 2025-11-21 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0003_notification_last_error'),
        ('todo_app', '0007_alter_todo_assignee_calendar_event_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='todo_app.todo'),
        ),
    ]
