# Generated by Django 5.2.7 on 2025-11-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0004_notification_task_id_notification_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='task_id',
            new_name='celery_task_id',
        ),
    ]
