# Generated by Django 5.2.7 on 2025-10-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_managers_teacherapproval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherapproval',
            options={'verbose_name': 'Approval', 'verbose_name_plural': 'Approvals'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
