# Generated by Django 5.2.7 on 2025-10-13 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_teacherapproval_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapproval',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
