# Generated by Django 5.2.7 on 2025-11-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_teacherapproval_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('dean', 'Dean'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
