# Generated by Django 5.2.7 on 2025-12-03 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeanApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'dean'}, on_delete=django.db.models.deletion.CASCADE, related_name='dean_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dean Approval',
                'verbose_name_plural': 'Dean Approvals',
            },
        ),
    ]
