# Generated by Django 5.2.7 on 2025-12-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_deanapproval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherapproval',
            options={'verbose_name': 'Teacher Approval', 'verbose_name_plural': 'Teacher Approvals'},
        ),
    ]
